### ISSUE TITLE
include a css preprocessor

### ISSUE THREAD

**Issue by cocodrino** [vasanthk/react-es6-webpack-boilerplate#1]
Hi...I'd suggest include a css preprocessor, they're used in almost any project today, thanks.

**Comment by vasanthk** [comment]
@cocodrino I consciously tried to keep the boilerplate as simple as possible to allow others to customize it with whatever plugins necessary.

Should be fairly easy to add CSS preprocessors via

`npm install less-loader` or `npm install sass-loader`

webpack.config.js

```
  module: {
    loaders: [
     {
        test: /\.jsx?$/,
        loaders: ['react-hot', 'babel'],
        include: path.join(__dirname, 'scripts')
      }, 

    // LESS
    {
      test: /\.less$/,
      loader: 'style!css!less'
    },

    // SASS
    {
      test: /\.scss$/,
      loader: 'style!css!sass'
    }]
  }
};
```

Moreover, I try to add styles in my JS - within the component
This is explained in the talk below and recommended by React Core team
http://blog.vjeux.com/2014/javascript/react-css-in-js-nationjs.html
