### ISSUE TITLE
Question: What happens after "run build"?

### ISSUE THREAD

**Issue by n3ssi3** [vasanthk/react-es6-webpack-boilerplate#12]
Hey there..

Sorry maybe my question is a bit stupid...
I just installed your boilerplate and it looks great. Light and nicely structured.
But what happens after I ran "build". I mean now I have the dist folder and everything, but this never gets loaded.
Can't I run the server on live and it takes the already finished bundle?
Maybe I am missing something...
Sorry to bother you :)

**Comment by vasanthk** [comment]
@n3ssi3 The `build` command is used mainly when you want to export your file to be published as a module or deployed for production. `dist` folder's files are minified/uglified and leaner in bytes.
For the purposes of testing out the boilerplate `npm start` should do. This loads the files via the dev server and live reloads changes. Let me know anything is not clear and I shall explain more.

**Comment by n3ssi3** [comment]
I mean on production, how do I run the project?
Shouldnt it be the same as on dev but instead of loading the js from webpack hot reload it should just load the static bundle?
Or do you have an other index.html on production than on dev?
I want to have a bundle.js for production ( and the backend developer) and for frontend dev I want the hot reload with webpack. But I have no idea how to switch from webpack to the already created bundle.

**Comment by vasanthk** [comment]
@n3ssi3 
This boilerplate is more on the component level, where you can use index.html to add in a demo and then export your component as a module which can eventually be imported in an app and used.
If you wanted to share the same dist version for development and production you might need to setup watchers for building it using `nodemon`.
