### ISSUE TITLE
Babel env isn't changed for prod; breaks builds

### ISSUE THREAD

**Issue by irskep** [vasanthk/react-es6-webpack-boilerplate#13]
The babelrc specifies an HMR transform for development. But the development transforms are applied even when using the production config, so production JS break due to the absence of the HMR runtime.

**Comment by irskep** [comment]
I worked around it by calling `BABEL_ENV=production webpack --config=webpack.config.production.js` when building.

**Comment by mnemanja** [comment]
I however still have this problem. This is the error message that I receive upon running `npm run build`:

```
$ npm run build

> react-es6-webpack-boilerplate@4.0.0 build C:\www\React2Do
> BABEL_ENV=production webpack --config=webpack.config.production.js

'BABEL_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by amilajack** [comment]
cross-env may have solved this issue. Try running with latest node and npm versions
