### ISSUE TITLE
linting errors with es2015 import syntax

### ISSUE THREAD

**Issue by battaile** [vasanthk/react-es6-webpack-boilerplate#2]
Hey vasanthk,
I'm getting 'illegal import declaration' at line 1 in app.js ( import React, {Component} from 'react';  ) when i 'npm run lint' ...does this happen for you as well?

**Comment by vasanthk** [comment]
It works fine for me.

Make sure your packages are up to date and also check if `modules` is set to `true` in your .eslintrc

```
"ecmaFeatures": {
    "modules": true
 }
```

**Comment by battaile** [comment]
Will do,thanks!

edit:  Apparently I left off the .eslintrc file when setting up my project, everything is working great now.  Thanks again for this template, its really helped me get off the ground

**Comment by vasanthk** [comment]
You're welcome :)
