### ISSUE TITLE
PR: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [vasanthk/react-es6-webpack-boilerplate#22]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by vasanthk** [comment]
Absolutely! This boilerplate a very much open to collaboration. Bring it on :)
