### ISSUE TITLE
Running npm build has no output of any kind

### ISSUE THREAD

**Issue by dandonahoe** [vasanthk/react-es6-webpack-boilerplate#26]
I ran `npm build` and there was no console or file output. Is that the correct command?

**Comment by vasanthk** [comment]
@dandonahoe Please try `npm run build`

**Comment by dandonahoe** [comment]
@vasanthk Thanks for the reply, I actually JUST figured it out. Turns out that `npm build` calls a node module called `cross-env` which needs to be globally installed on the machine to have the build work. Oddly enough, if it's not installed, npm doesn't give any error at all. A quick `npm install cross-env -g` fixed everything and the build works great.

Probably worth noting that in the documentation.

Thanks!

**Comment by vasanthk** [comment]
@dandonahoe It gets installed as a part of this boilerplate. You'll need to do `npm i` before you build it. Doesn't need to be global.

**Comment by dandonahoe** [comment]
@vasanthk Yeah that's what had me really confused. I ran `cross-env` in the console within the project directory and got `command not found`, even reloaded the console just to be sure. But the instant I made it global, started working immediately. Might just be something wonky about my setup.
