### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by zedd45** [vasanthk/react-es6-webpack-boilerplate#7]
I know everyone uses different tools for testing, but I was wondering if you had plans, or were willing to accept PRs for an `npm test` target?   I'm not sure if your intentions are to keep this repo lean & unopionanted, or if you would consider something like a fork of this repo did with [mvader/react-es6-webpack-karma-boilerplate](https://github.com/mvader/react-es6-webpack-karma-boilerplate) ?

I want to use the fork in question for my project, but it's pretty dated, and you have a lot more activity in your repo.

I'd be happy to submit a PR if this is something you are willing to consider.

**Comment by vasanthk** [comment]
@zedd45 
Thank you for opening this discussion.

I feel a lightweight boilerplate might help folks to get started quickly with React quickly w/o much overhead. But, we could also expose the option to pick/choose boilerplates with a lot more features (testing/other bundlers/lints etc)

What do you feel about keeping Master as a lightweight version and having separate branches for other integrations (react-es6-webpack-karma-boilerplate etc), We can link to it from the top of master's README for better visibility to users.

Let me know if you have any other suggestions as well :)

**Comment by zedd45** [comment]
I think that idea is workable.  It would allow the "downstream" branches to receive the updates from master, and Github users should be familiar enough to switch branches to get the boilerplate they want. 

I'm not opposed to doing this on a fork, either; my biggest concern is staying in sync with `master`.  I'm less concerned about the methodology, and more concerned about the outcome (in this case, at least).

**Comment by vasanthk** [comment]
@zedd45 Sounds good. Branching seems easier to stay in sync.
I can either create a branch for you to send in a PR or add you as a collaborator for the repo.
Whatever you prefer.

**Comment by zedd45** [comment]
Whatever you think makes sense. I think the initial work shouldn't be too hard.  It's always the keeping it up to date part that takes more effort! :smile:

**Comment by vasanthk** [comment]
@zedd45 Alright cool :)
Have added you as a collaborator. Feel free to add a new branch for addons and we can link to the main readme. Thanks!

**Comment by zedd45** [comment]
I haven't had a chance to work on this lately due to other obligations, but I found something promising, or at least interesting, here: 
https://github.com/lelandrichardson/enzyme-example-karma-webpack

**Comment by vasanthk** [comment]
@zedd45 I have been hearing a lot of good things about enzyme. Will be trying it out some time this month.

**Comment by zedd45** [comment]
Yeah, what I've read so far, I really dig.  It reminds me of [`jasmine-jquery`](https://github.com/velesin/jasmine-jquery) in a way :+1:
