### ISSUE TITLE
react-transform-hmr bug in production

### ISSUE THREAD

**Issue by charlesvdv** [vasanthk/react-es6-webpack-boilerplate#9]
Hello, 

First of all, thank you a lot for your boilerplate. It's great for the beginner but I have a little problem with the production (when I run 'npm run build'). When I load the program in my browser, I got :

"Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr"

And when I search a little in the react-transform-hmr repository, I got this issue : 
https://github.com/gaearon/react-transform-hmr/issues/38
https://github.com/gaearon/react-transform-hmr/issues/5
https://github.com/gaearon/react-transform-hmr/issues/8

It appears that the react-transform-hmr should not be loaded in the .babelrc configuration file but in the webpack dev configuration file.

**Comment by vasanthk** [comment]
@charlesvdv Thank you for the detailed description.
A busy week ahead, so I'll get to it in a few days.
If you do have it fixed, please send in a PR. I will gladly merge it in. Thanks :)

**Comment by charlesvdv** [comment]
Ok no problem :) if I have time I'll look into it

**Comment by erosenberg** [comment]
I'm having this problem as well :)

**Comment by vasanthk** [comment]
@erosenberg Merged in the PR from @charlesvdv 
Props to him.. :clap:
